name: trending_movies
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  connectivity_plus: ^2.2.0
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
